"""
Production Configuration for RFP System
Michigan Technological University - Institute of Computing and Cybersystems
"""
from pathlib import Path

# Base directory
BASE_DIR = Path(__file__).parent.parent

# Database settings
DATABASE_PATH = BASE_DIR / "data" / "rfp_production.db"

# Google Sheets configuration
GOOGLE_SHEETS_ID = "" # ICC AI-Enabled RFP Search Form (Responses)
GOOGLE_SHEETS_RANGE = "'Form Responses 1'!A:Z"

# Gmail API configuration
CREDENTIALS_FILE = BASE_DIR / "config" / "icc-intake_credentials.json"
TOKEN_FILE = BASE_DIR / "config" / "token.json"
SCOPES = [
    "https://www.googleapis.com/auth/gmail.compose",
    "https://www.googleapis.com/auth/spreadsheets.readonly"
]

# Email settings
SENDER_EMAIL = "icc-intake@mtu.edu"
CC_RECIPIENTS = ["ajstump@mtu.edu", "townsend@mtu.edu"]

# Email template
EMAIL_TEMPLATE = """
Hello,

This is an automated email from the ICC Proposal-Enabled AI Support Initiative. An HTML output file generated by Perplexity AI containing relevant RFP opportunities based on your Google Form responses is attached.

To access the information, you can download the HTML file and open it in your browser.

Feel free to reply to this email if you are unable to access the information, and if you would like to revise your answers, you can revise your responses to the Google Form.

Thank you,

Center for AI
Institute of Computing and Cybersystems
Michigan Technological University

"""

# Perplexity AI configuration
PERPLEXITY_API_URL = "https://api.perplexity.ai/chat/completions"
PERPLEXITY_API_KEY = "" #Perplexity API Key
PERPLEXITY_MODEL = "sonar-deep-research"
PERPLEXITY_TEMPERATURE = 0.5

# AI Prompt configuration
INSTITUTION_NAME = "Michigan Technological University"


PROMPT_INSTRUCTIONS = (
    f"I am a professor at {INSTITUTION_NAME}, seeking relevant upcoming grant opportunities "
    f"- **DO NOT** include: RFPs issued by {INSTITUTION_NAME}; RFPs with deadlines that have already passed or expired RFPs.\n"
)

PROMPT_REQUEST = (
    "Search for at least **10 eligible and active U.S.-based RFPs** that align with my research interests.\n\n"
    "**Start your response with a markdown table** listing the opportunities. Do not include any explanation before the table.\n\n"
    "The table should have the following columns:\n"
    "- Funding Agency\n"
    "- Program Name\n"
    "- Focus Area \n"
    "- Award Range \n"
    "- Clickable Website Link\n"
    "- Deadline \n\n"
    "Make sure the table is at the top of the generated results, you can provide the information consisely about notable opportunities. "
    "Ensure the results are current, relevant, and aligned with common academic grant interests."
)

# Directory structure
DATA_DIR = BASE_DIR / "data"
LOGS_DIR = BASE_DIR / "logs"
OUTPUT_DIR = BASE_DIR / "output"
FACULTY_DIRS = OUTPUT_DIR / "faculty"

# Frequency mapping (days)
FREQUENCY_MAPPING = {
    'weekly': 7,
    'biweekly': 14,
    'monthly': 30,
    'one response' : None
}

# Column mapping for Google Sheets
COLUMN_MAPPING = {
    'timestamp': 'Timestamp',
    'email': 'Email Address',
    'research_area': 'Briefly describe your RFP research area of interest.',
    'keywords': 'List 3-5 relevant keywords',
    'eligibility_constraints': 'Are there any constraints on your eligibility to RFP\'s? If there are no constraints, please state "no".',
    'early_career': 'Are you an early career researcher?',
    'funding_types': 'What types of funding opportunities are you interested in?',
    'rfp_size': 'What is the size of the RFP you are interested in?',
    'submission_timeline': 'When would you like to submit a proposal?',
    'preferred_funding_sources': 'Please list preferred or previous funding sources.',
    'frequency': 'How often would you like to receive AI-generated RFP matches?',
    'additional_info': 'Please add any additional information or previous funding sources you feel would be helpful.',
    'documents': 'You are welcome to upload any documents, such as white papers.'
}

# System settings
MAX_RETRIES = 3
DUPLICATE_CHECK_DAYS = 7
LOG_RETENTION_DAYS = 30
BATCH_SIZE = 4  # Process 4 faculty per batch with staggered starts
PARALLEL_PROCESSING = True
API_TIMEOUT = 600  # Increased to 10 minutes for deep research model
RETRY_DELAY_BASE = 5  # Base delay in seconds for exponential backoff

# Create directories
for directory in [DATA_DIR, LOGS_DIR, OUTPUT_DIR, FACULTY_DIRS]:
    directory.mkdir(parents=True, exist_ok=True)
